name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install tools
      run: make install
    - name: Run CI
      run: make ci
